//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gramatica.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="gramaticaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IgramaticaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] gramaticaParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] gramaticaParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstrucciones([NotNull] gramaticaParser.InstruccionesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstrucciones([NotNull] gramaticaParser.InstruccionesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruccion([NotNull] gramaticaParser.InstruccionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruccion([NotNull] gramaticaParser.InstruccionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint([NotNull] gramaticaParser.PrintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint([NotNull] gramaticaParser.PrintContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] gramaticaParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] gramaticaParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Decimal</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimal([NotNull] gramaticaParser.DecimalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Decimal</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimal([NotNull] gramaticaParser.DecimalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDiv([NotNull] gramaticaParser.MulDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDiv([NotNull] gramaticaParser.MulDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSub([NotNull] gramaticaParser.AddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSub([NotNull] gramaticaParser.AddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParens([NotNull] gramaticaParser.ParensContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParens([NotNull] gramaticaParser.ParensContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Cadena</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCadena([NotNull] gramaticaParser.CadenaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Cadena</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCadena([NotNull] gramaticaParser.CadenaContext context);
}
